repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^.*yml$
        
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        exclude: ^.*yml$
        language_version: python3
