repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^.*yml$
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5
    hooks:
    - id: autopep8
        
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: ^.*yml$
