name: Doc-Pilot
on: [push, pull_request]

permissions: 
    actions: read
    contents: write

jobs:
  add-docstring:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              repository: ${{github.repository}}
              token: ${{secrets.GITHUB_TOKEN}}
              ref: ${{github.head_ref}}
              submodules: "recursive"
              fetch-depth: 100

          - name: Get files Changes
            uses: lots0logs/gh-action-get-changed-files@2.2.2
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
        
          - name: Fetch Commit Changes
            id: fetch_changes
            run: |
              cd DocPilot
              # files changed can be accessed through ${HOME}/files.json
              git diff HEAD~1 HEAD --output="temp.txt"
              grep '^\+' temp.txt > diff.txt     

          - name: Install Python Clients
            run: |
              pip install anthropic

          - name: Run Claude Magic
            run: |
              cd DocPilot
              python3 claude/script.py ${{secrets.ANTHROPIC_API_KEY}}

          - name: Check if there are changes 📝
            id: check
            run: |
                if [[ -n "$(git status --porcelain)" ]]; then
                  echo "changes=true" >> $GITHUB_OUTPUT
                fi
          
          - name: Update file with Docstring
            if: steps.check.outputs.changes == 'true'
            run: |
              git config --local user.email "samuel_e_armstrong@yahoo.co.uk"
              git config --local user.name "Sam-Armstrong"
              git add .
              git commit -m "add docstring"
              git push